settings:
  title: 'Estado Servidores'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos Los Sistemas Est치n Operativos'
  notAllmonitorsOperational: 'No Todos Los Sitemas Est치n Operativos'
  monitorLabelOperational: 'Operativo'
  monitorLabelNotOperational: 'No Operativo'
  monitorLabelNoData: 'No hay datos'
  dayInHistogramNoData: 'No hay datos'
  dayInHistogramOperational: 'Todo bien'
  dayInHistogramNotOperational: ' incidente(s)' # xx incidentes(s) grabados

monitors:
  - id: santoslife.net1 # unique identifier
    name: P치gina Web
    description: 'P치gina web del servidor.' # default=empty
    url: 'https://santoslife.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
